source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
def pods
pod 'SnapKit', '~> 0.15.0'

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'R.swift'
pod 'ObjectMapper'
end

target 'SwfitWeiBo' do
pods

end